# Generated by Django 3.0.10 on 2021-02-20 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210220_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp_graph',
            name='company',
            field=models.CharField(blank=True, default='company name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comp_graph',
            name='number',
            field=models.CharField(blank=True, default='2000', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='mess',
            field=models.TextField(blank=True, default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='brochureurl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='stulisturl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='Batch_end',
            field=models.PositiveIntegerField(blank=True, default=2003, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='Batch_start',
            field=models.PositiveIntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='no_of_stud',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plc_comp',
            name='comp_name',
            field=models.CharField(blank=True, default='NULL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plc_comp',
            name='imgurl',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='d_o_b',
            field=models.DateField(default=datetime.datetime(2021, 2, 20, 6, 21, 43, 3827, tzinfo=utc)),
        ),
    ]
