# Generated by Django 3.0.10 on 2021-02-20 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210220_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='d_o_b',
            field=models.DateField(default=datetime.datetime(2021, 2, 20, 6, 24, 42, 850103, tzinfo=utc)),
        ),
    ]
