# Generated by Django 3.0.10 on 2021-02-20 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210220_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='d_o_b',
            field=models.DateField(default=datetime.datetime(2021, 2, 20, 6, 27, 38, 287155, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='files',
            table='files',
        ),
    ]
